<?php

Route::apiResources([
    'audits' => \App\Http\Controllers\AuditController::class,
    'business_grades' => \App\Http\Controllers\BusinessGradeController::class,
    'business_posts' => \App\Http\Controllers\BusinessPostController::class,
    'business_schemes' => \App\Http\Controllers\BusinessSchemeController::class,
    'business_units' => \App\Http\Controllers\BusinessUnitController::class,
    'cache' => \App\Http\Controllers\CacheController::class,
    'cache_locks' => \App\Http\Controllers\CacheLockController::class,
    'communities' => \App\Http\Controllers\CommunityController::class,
    'community_members' => \App\Http\Controllers\CommunityMemberController::class,
    'community_preferences' => \App\Http\Controllers\CommunityPreferenceController::class,
    'departments' => \App\Http\Controllers\DepartmentController::class,
    'department_preferences' => \App\Http\Controllers\DepartmentPreferenceController::class,
    'employment_posts' => \App\Http\Controllers\EmploymentPostController::class,
    'events' => \App\Http\Controllers\EventController::class,
    'event_attendance' => \App\Http\Controllers\EventAttendanceController::class,
    'failed_jobs' => \App\Http\Controllers\FailedJobController::class,
    'invitations' => \App\Http\Controllers\InvitationController::class,
    'jobs' => \App\Http\Controllers\JobController::class,
    'job_batches' => \App\Http\Controllers\JobBatchController::class,
    'migrations' => \App\Http\Controllers\MigrationController::class,
    'model_has_permissions' => \App\Http\Controllers\ModelHasPermissionController::class,
    'model_has_roles' => \App\Http\Controllers\ModelHasRoleController::class,
    'notifications' => \App\Http\Controllers\NotificationController::class,
    'password_reset_tokens' => \App\Http\Controllers\PasswordResetTokenController::class,
    'permissions' => \App\Http\Controllers\PermissionController::class,
    'posts' => \App\Http\Controllers\PostController::class,
    'post_accessibilities' => \App\Http\Controllers\PostAccessibilityController::class,
    'post_comments' => \App\Http\Controllers\PostCommentController::class,
    'preference_schemas' => \App\Http\Controllers\PreferenceSchemaController::class,
    'profiles' => \App\Http\Controllers\ProfileController::class,
    'resources' => \App\Http\Controllers\ResourceController::class,
    'resource_access' => \App\Http\Controllers\ResourceAccessController::class,
    'roles' => \App\Http\Controllers\RoleController::class,
    'role_has_permissions' => \App\Http\Controllers\RoleHasPermissionController::class,
    'sessions' => \App\Http\Controllers\SessionController::class,
    'settings' => \App\Http\Controllers\SettingController::class,
    'supervisors' => \App\Http\Controllers\SupervisorController::class,
    'tasks' => \App\Http\Controllers\TaskController::class,
    'task_items' => \App\Http\Controllers\TaskItemController::class,
    'users' => \App\Http\Controllers\UserController::class,
    'user_preferences' => \App\Http\Controllers\UserPreferenceController::class,
]);
